apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-cicdapp
  namespace: jenkin
  labels: 
    app: myjavaapp-cicdapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myjavaapp-cicdapp
  template:
    metadata:
      labels:
        app: myjavaapp-cicdapp
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: myjavaapp-cicdapp
          image: 35.247.121.190:8083/springapp:104
          command: ["/bin/sh"]
          args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /home
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /home
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 256Mi
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true